HospitalMgmtSystem/Controllers/DoctorsController.cs
using HospitalMgmtSystem.DAL.Data.Model;
using HospitalMgmtSystem.Services.Services;
using HospitalMgmtSystem.Services.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;

namespace HospitalMgmtSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DoctorsController : Controller
    {
        private readonly ILogger<UserDoctorRegisterModel> _logger;
        private readonly IDoctorService _doctorService;
        private readonly IUserService _userService;

        public DoctorsController(ILogger<UserDoctorRegisterModel> logger, IDoctorService doctorService, IUserService userService)
        {
            this._logger = logger;
            this._doctorService = doctorService;
            this._userService = userService;
        }

        // GET: Doctors
        public async Task<IActionResult> Index([Bind] int page, [Bind] int resultsPerPage)
        {
            page = page == 0 ? 1 : page;
            resultsPerPage = resultsPerPage == 0 ? 5 : resultsPerPage;

            var result = await _doctorService.GetAllDoctors();

            int skip = (page - 1) * resultsPerPage;

            var data = result.Skip(skip).Take(resultsPerPage);
            ViewData["Next"] = result.Count() - skip - resultsPerPage > 0 ? page + 1 : 1;
            ViewData["Previous"] = page <= 1 ? 1 : page - 1;
            ViewData["ResultsPerPage"] = resultsPerPage;
            return View(data);
        }

        // GET: Doctors/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var doc = await _doctorService.GetDoctorByID(id);

            if (doc == null)
            {
                return NotFound();
            }

            var doctor = new UserDoctorViewModel()
            {
                ID = doc.ID,
                Name = doc.Users.FirstName + " " + doc.Users.LastName,
                Address = doc.Users.Address,
                Email = doc.Users.Email,
                Number = doc.Users.Number,
                Specialization = doc.Specialization.ToString(),
                YearsOfExperience = doc.YearsOfExperience,
                AdditionalInformation = doc.AdditionalInfo,
            };

            return View(doctor);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID, FirstName, LastName, Number, Address, Email, Specialization, YearsOfExperience, AdditionalInfo")] UserDoctorRegisterModel receivedDoctor)
        {
            receivedDoctor.ID = 0;


            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser()
                {
                    FirstName = receivedDoctor.FirstName,
                    LastName = receivedDoctor.LastName,
                    Number = receivedDoctor.Number,
                    Address = receivedDoctor.Address,
                    Email = receivedDoctor.Email,
                    UserName = receivedDoctor.Email,
                    IsActive = true,
                    EmailConfirmed = true,
                    Role = Role.Doctor
                };

                Doctor doctor = new Doctor()
                {
                    Specialization = receivedDoctor.Specialization,
                    YearsOfExperience = receivedDoctor.YearsOfExperience,
                    AdditionalInfo = receivedDoctor.AdditionalInfo,
                    IsActive = true
                };

                bool isAdded = await _userService.CreateUser(user, "Doctor");

                if (isAdded)
                {
                    doctor.UserId = user.Id;
                    await _doctorService.CreateDoctor(doctor);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }

        // GET: Doctors/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var res = await _doctorService.GetDoctorByID(id);

            var doctor = new UserDoctorRegisterModel()
            {
                ID = res.ID,
                YearsOfExperience = res.YearsOfExperience,
                AdditionalInfo = res.AdditionalInfo,
                Specialization = res.Specialization,

                FirstName = res.Users.FirstName,
                LastName = res.Users.LastName,
                Number = res.Users.Number,
                Address = res.Users.Address,
                Email = res.Users.Email
            };

            if (doctor == null)
            {
                return NotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID, FirstName, LastName, Number, Address, Email, Specialization, YearsOfExperience, AdditionalInfo")] UserDoctorRegisterModel receivedDoctor)
        {
            if (id != receivedDoctor.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var doctor = await _doctorService.GetDoctorByID(receivedDoctor.ID);

                    doctor.Users.FirstName = receivedDoctor.FirstName;
                    doctor.Users.LastName = receivedDoctor.LastName;
                    doctor.Users.Number = receivedDoctor.Number;
                    doctor.Users.Address = receivedDoctor.Address;

                    doctor.Specialization = receivedDoctor.Specialization;
                    doctor.YearsOfExperience = receivedDoctor.YearsOfExperience;
                    doctor.AdditionalInfo = receivedDoctor.AdditionalInfo;

                    await _doctorService.UpdateDoctor(doctor);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(receivedDoctor.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(receivedDoctor);
        }

        // GET: Doctors/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var doctor = await _doctorService.GetDoctorByID(id);

            UserDoctorViewModel model = new UserDoctorViewModel()
            {
                ID = doctor.ID,
                Name = doctor.Users.FirstName + " " + doctor.Users.LastName,
                Specialization = doctor.Specialization.ToString(),
                YearsOfExperience = doctor.YearsOfExperience,
                Email = doctor.Users.Email,
                AdditionalInformation = doctor.AdditionalInfo,
                Number = doctor.Users.Number
            };

            if (doctor == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctor = await _doctorService.GetDoctorByID(id);


            doctor.IsActive = false;
            doctor.Users.IsActive = false;

            await _doctorService.UpdateDoctor(doctor);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Search(string id)
        {
            if (id == null)
            {
                return BadRequest(new { status = "fail" });
            }

            var filteredResult = await _doctorService.Search(id);



            if (filteredResult == null)
            {
                return BadRequest(new { status = "fail" });
            }

            return Ok(new
            {
                status = "success",
                results = filteredResult.Count(),
                data = filteredResult
            });
        }

        private bool DoctorExists(int id)
        {
            return _doctorService.GetDoctorByID(id) != null;
        }
    }
}

HospitalMgmtSystem/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HospitalMgmtSystem.DAL.Data;
using HospitalMgmtSystem.DAL.Data.Model;
using HospitalMgmtSystem.Services.ViewModels;
using Microsoft.Extensions.Logging;
using HospitalMgmtSystem.Services.Services;
using Microsoft.AspNetCore.Authorization;

namespace HospitalMgmtSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PatientsController : Controller
    {
        private readonly ILogger<UserPatientRegisterModel> _logger;
        private readonly IPatientService _patientService;
        private readonly IUserService _userService;

        public PatientsController(ILogger<UserPatientRegisterModel> logger, IPatientService patientService, IUserService userService)
        {
            this._logger = logger;
            this._patientService = patientService;
            this._userService = userService;
        }

        // GET: Patients
        public async Task<IActionResult> Index()
        {
            return View(await _patientService.GetAllPatients());
        }

        // GET: Patients/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var res = await _patientService.GetPatientByID(id);
            if (res == null)
            {
                return NotFound();
            }
            var patient = new UserPatientViewModel()
            {
                ID = res.ID,
                Name = res.Users.FirstName + " " + res.Users.LastName,
                Email = res.Users.Email,
                Address = res.Users.Address,
                Number = res.Users.Number,
                BloodGroup = res.BloodGroup,
                MedicalHistory = res.MedicalHistory,
                AdditionalInfo = res.AdditionalInfo
            };

            return View(patient);
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID, FirstName, LastName, Number, Address, Email,BloodGroup,MedicalHistory,AdditionalInfo")] UserPatientRegisterModel receivedPatient)
        {
            receivedPatient.ID = 0;

            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser()
                {
                    FirstName = receivedPatient.FirstName,
                    LastName = receivedPatient.LastName,
                    Number = receivedPatient.Number,
                    Address = receivedPatient.Address,
                    Email = receivedPatient.Email,
                    UserName = receivedPatient.Email,
                    IsActive = true,
                    EmailConfirmed = true,
                    Role = Role.Patient
                };

                Patient patient = new Patient()
                {
                    MedicalHistory = receivedPatient.MedicalHistory,
                    BloodGroup = receivedPatient.BloodGroup,
                    AdditionalInfo = receivedPatient.AdditionalInfo,
                    IsActive = true
                };

                bool isAdded = await _userService.CreateUser(user, "Patient");

                if (isAdded)
                {
                    patient.UserId = user.Id;
                    await _patientService.CreatePatient(patient);

                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Index));
            }

            return View(receivedPatient);
        }

        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var res = await _patientService.GetPatientByID(id);

            if (res == null)
            {
                return NotFound();
            }

            var patient = new UserPatientRegisterModel()
            {
                ID = res.ID,
                MedicalHistory = res.MedicalHistory,
                BloodGroup = res.BloodGroup,
                AdditionalInfo = res.AdditionalInfo,

                FirstName = res.Users.FirstName,
                LastName = res.Users.LastName,
                Number = res.Users.Number,
                Address = res.Users.Address,
                Email = res.Users.Email
            };

            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID, FirstName, LastName, Number, Address, Email,BloodGroup,MedicalHistory,AdditionalInfo")] UserPatientRegisterModel receivedPatient)
        {
            if (id != receivedPatient.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var patient = await _patientService.GetPatientByID(receivedPatient.ID);
                    patient.Users.FirstName = receivedPatient.FirstName;
                    patient.Users.LastName = receivedPatient.LastName;
                    patient.Users.Number = receivedPatient.Number;
                    patient.Users.Address = receivedPatient.Address;

                    patient.MedicalHistory = receivedPatient.MedicalHistory;
                    patient.BloodGroup = receivedPatient.BloodGroup;
                    patient.AdditionalInfo = receivedPatient.AdditionalInfo;

                    await _patientService.UpdatePatient(patient);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(receivedPatient.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(receivedPatient);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var res = await _patientService.GetPatientByID(id);

            if (res == null)
            {
                return NotFound();
            }

            UserPatientViewModel patient = new UserPatientViewModel()
            {
                ID = res.ID,
                Name = res.Users.FirstName + " " + res.Users.LastName,
                Email = res.Users.Email,
                Address = res.Users.Address,
                Number = res.Users.Number,
                BloodGroup = res.BloodGroup,
                MedicalHistory = res.MedicalHistory,
                AdditionalInfo = res.AdditionalInfo
            };

            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patient = await _patientService.GetPatientByID(id);

            patient.IsActive = false;
            patient.Users.IsActive = false;

            await _patientService.UpdatePatient(patient);

            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
            return _patientService.GetPatientByID(id) != null;
        }

        public async Task<IActionResult> Search(string id)
        {
            if (id == null)
            {
                return BadRequest(new { status = "fail" });
            }

            var filteredResult = await _patientService.Search(id);


            if (filteredResult == null)
            {
                return BadRequest(new { status = "fail" });
            }

            return Ok(new
            {
                status = "success",
                results = filteredResult.Count(),
                data = filteredResult
            });
        }
    }
}

HospitalMgmtSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalMgmtSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Stylesheet", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hospital</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_NavigationPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HospitalMgmtSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HospitalMgmtSystem/Views/Shared/_NavigationPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    if (SignInManager.IsSignedIn(User))
    {
        if (User.IsInRole("Admin"))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Doctors" asp-action="Index">Doctor</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Patients" asp-action="Index">Patient</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="CasePapers" asp-action="Index">CasePaper</a>
            </li>
        }
        else if (User.IsInRole("Doctor"))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Doctors" asp-action="Index">Today's Appoinments</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Patients" asp-action="Index">Past Appoinments</a>
            </li>
        }
        else if (User.IsInRole("Patient"))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Doctors" asp-action="Index">Active Appoinments</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-controller="Patients" asp-action="Index">Past Appoinments</a>
            </li>
        }
    }
}

HospitalMgmtSystem/Views/Shared/_SearchBar.cshtml
<div class="col-4">
    <form id="searchForm" class="row">
        <div class="col-10 pr-1">
            <div class="form-group">
                <input type="text" class="form-control" id="key" name="key" placeholder="Search" required />
            </div>
        </div>
        <div class="col-2 pl-0">
            <div class="form-group">
                <button class="btn btn-primary" id="searchBtn"><i class="bi bi-search"></i></button>
            </div>
        </div>
    </form>
</div>